# Generated by Django 4.2.23 on 2025-09-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_is_default_alter_category_user'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Insert main categories
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (1, NULL, NULL, true),   -- Income
            (2, NULL, NULL, true),   -- Food & Dining
            (3, NULL, NULL, true),   -- Transportation
            (4, NULL, NULL, true),   -- Shopping
            (5, NULL, NULL, true),   -- Entertainment
            (6, NULL, NULL, true),   -- Health & Fitness
            (7, NULL, NULL, true),   -- Home
            (8, NULL, NULL, true),   -- Education
            (9, NULL, NULL, true),   -- Travel
            (10, NULL, NULL, true),  -- Financial
            (11, NULL, NULL, true);  -- Personal Care
            
            -- Insert subcategories for Income (parent_id = 1)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (12, 1, NULL, true),   -- Salary
            (13, 1, NULL, true),   -- Freelance
            (14, 1, NULL, true),   -- Business Income
            (15, 1, NULL, true),   -- Investment Returns
            (16, 1, NULL, true),   -- Rental Income
            (17, 1, NULL, true),   -- Gifts Received
            (18, 1, NULL, true);   -- Other Income
            
            -- Insert subcategories for Food & Dining (parent_id = 2)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (19, 2, NULL, true),   -- Groceries
            (20, 2, NULL, true),   -- Restaurants
            (21, 2, NULL, true),   -- Fast Food
            (22, 2, NULL, true),   -- Coffee Shops
            (23, 2, NULL, true);   -- Alcohol & Bars
            
            -- Insert subcategories for Transportation (parent_id = 3)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (24, 3, NULL, true),   -- Gas & Fuel
            (25, 3, NULL, true),   -- Car Maintenance
            (26, 3, NULL, true),   -- Public Transportation
            (27, 3, NULL, true),   -- Taxi & Rideshare
            (28, 3, NULL, true),   -- Car Insurance
            (29, 3, NULL, true);   -- Car Payment
            
            -- Insert subcategories for Shopping (parent_id = 4)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (30, 4, NULL, true),   -- Clothing
            (31, 4, NULL, true),   -- Electronics
            (32, 4, NULL, true),   -- Home & Garden
            (33, 4, NULL, true),   -- Books & Media
            (34, 4, NULL, true);   -- Gifts
            
            -- Insert subcategories for Entertainment (parent_id = 5)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (35, 5, NULL, true),   -- Movies & Theater
            (36, 5, NULL, true),   -- Sports & Recreation
            (37, 5, NULL, true),   -- Hobbies
            (38, 5, NULL, true),   -- Subscriptions
            (39, 5, NULL, true);   -- Games
            
            -- Insert subcategories for Health & Fitness (parent_id = 6)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (40, 6, NULL, true),   -- Medical
            (41, 6, NULL, true),   -- Pharmacy
            (42, 6, NULL, true),   -- Gym & Fitness
            (43, 6, NULL, true),   -- Health Insurance
            (44, 6, NULL, true);   -- Dental
            
            -- Insert subcategories for Home (parent_id = 7)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (45, 7, NULL, true),   -- Rent/Mortgage
            (46, 7, NULL, true),   -- Utilities
            (47, 7, NULL, true),   -- Internet & Phone
            (48, 7, NULL, true),   -- Home Maintenance
            (49, 7, NULL, true);   -- Furniture
            
            -- Insert subcategories for Education (parent_id = 8)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (50, 8, NULL, true),   -- Tuition
            (51, 8, NULL, true),   -- Books & Supplies
            (52, 8, NULL, true),   -- Online Courses
            (53, 8, NULL, true);   -- Training
            
            -- Insert subcategories for Travel (parent_id = 9)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (54, 9, NULL, true),   -- Flights
            (55, 9, NULL, true),   -- Hotels
            (56, 9, NULL, true),   -- Car Rental
            (57, 9, NULL, true),   -- Travel Insurance
            (58, 9, NULL, true);   -- Activities
            
            -- Insert subcategories for Financial (parent_id = 10)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (59, 10, NULL, true),  -- Bank Fees
            (60, 10, NULL, true),  -- Investments
            (61, 10, NULL, true),  -- Insurance
            (62, 10, NULL, true),  -- Taxes
            (63, 10, NULL, true);  -- Loans
            
            -- Insert subcategories for Personal Care (parent_id = 11)
            INSERT INTO expenses_category (id, parent_id, user_id, is_default) VALUES
            (64, 11, NULL, true),  -- Haircut
            (65, 11, NULL, true),  -- Cosmetics
            (66, 11, NULL, true);  -- Spa & Wellness
            
            -- Insert English translations for main categories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (1, 'en', 'Income'),
            (2, 'en', 'Food & Dining'),
            (3, 'en', 'Transportation'),
            (4, 'en', 'Shopping'),
            (5, 'en', 'Entertainment'),
            (6, 'en', 'Health & Fitness'),
            (7, 'en', 'Home'),
            (8, 'en', 'Education'),
            (9, 'en', 'Travel'),
            (10, 'en', 'Financial'),
            (11, 'en', 'Personal Care');
            
            -- Insert Spanish translations for main categories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (1, 'es', 'Ingresos'),
            (2, 'es', 'Comida y Restaurantes'),
            (3, 'es', 'Transporte'),
            (4, 'es', 'Compras'),
            (5, 'es', 'Entretenimiento'),
            (6, 'es', 'Salud y Fitness'),
            (7, 'es', 'Hogar'),
            (8, 'es', 'Educación'),
            (9, 'es', 'Viajes'),
            (10, 'es', 'Financiero'),
            (11, 'es', 'Cuidado Personal');
            
            -- Insert English translations for Income subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (12, 'en', 'Salary'),
            (13, 'en', 'Freelance'),
            (14, 'en', 'Business Income'),
            (15, 'en', 'Investment Returns'),
            (16, 'en', 'Rental Income'),
            (17, 'en', 'Gifts Received'),
            (18, 'en', 'Other Income');
            
            -- Insert Spanish translations for Income subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (12, 'es', 'Salario'),
            (13, 'es', 'Trabajo Independiente'),
            (14, 'es', 'Ingresos del Negocio'),
            (15, 'es', 'Retornos de Inversión'),
            (16, 'es', 'Ingresos por Alquiler'),
            (17, 'es', 'Regalos Recibidos'),
            (18, 'es', 'Otros Ingresos');
            
            -- Insert English translations for Food & Dining subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (19, 'en', 'Groceries'),
            (20, 'en', 'Restaurants'),
            (21, 'en', 'Fast Food'),
            (22, 'en', 'Coffee Shops'),
            (23, 'en', 'Alcohol & Bars');
            
            -- Insert Spanish translations for Food & Dining subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (19, 'es', 'Supermercado'),
            (20, 'es', 'Restaurantes'),
            (21, 'es', 'Comida Rápida'),
            (22, 'es', 'Cafeterías'),
            (23, 'es', 'Alcohol y Bares');
            
            -- Insert English translations for Transportation subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (24, 'en', 'Gas & Fuel'),
            (25, 'en', 'Car Maintenance'),
            (26, 'en', 'Public Transportation'),
            (27, 'en', 'Taxi & Rideshare'),
            (28, 'en', 'Car Insurance'),
            (29, 'en', 'Car Payment');
            
            -- Insert Spanish translations for Transportation subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (24, 'es', 'Gasolina y Combustible'),
            (25, 'es', 'Mantenimiento del Auto'),
            (26, 'es', 'Transporte Público'),
            (27, 'es', 'Taxi y Viajes Compartidos'),
            (28, 'es', 'Seguro del Auto'),
            (29, 'es', 'Pago del Auto');
            
            -- Insert English translations for Shopping subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (30, 'en', 'Clothing'),
            (31, 'en', 'Electronics'),
            (32, 'en', 'Home & Garden'),
            (33, 'en', 'Books & Media'),
            (34, 'en', 'Gifts');
            
            -- Insert Spanish translations for Shopping subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (30, 'es', 'Ropa'),
            (31, 'es', 'Electrónicos'),
            (32, 'es', 'Hogar y Jardín'),
            (33, 'es', 'Libros y Medios'),
            (34, 'es', 'Regalos');
            
            -- Insert English translations for Entertainment subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (35, 'en', 'Movies & Theater'),
            (36, 'en', 'Sports & Recreation'),
            (37, 'en', 'Hobbies'),
            (38, 'en', 'Subscriptions'),
            (39, 'en', 'Games');
            
            -- Insert Spanish translations for Entertainment subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (35, 'es', 'Cine y Teatro'),
            (36, 'es', 'Deportes y Recreación'),
            (37, 'es', 'Pasatiempos'),
            (38, 'es', 'Suscripciones'),
            (39, 'es', 'Juegos');
            
            -- Insert English translations for Health & Fitness subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (40, 'en', 'Medical'),
            (41, 'en', 'Pharmacy'),
            (42, 'en', 'Gym & Fitness'),
            (43, 'en', 'Health Insurance'),
            (44, 'en', 'Dental');
            
            -- Insert Spanish translations for Health & Fitness subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (40, 'es', 'Médico'),
            (41, 'es', 'Farmacia'),
            (42, 'es', 'Gimnasio y Fitness'),
            (43, 'es', 'Seguro de Salud'),
            (44, 'es', 'Odontología');
            
            -- Insert English translations for Home subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (45, 'en', 'Rent/Mortgage'),
            (46, 'en', 'Utilities'),
            (47, 'en', 'Internet & Phone'),
            (48, 'en', 'Home Maintenance'),
            (49, 'en', 'Furniture');
            
            -- Insert Spanish translations for Home subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (45, 'es', 'Alquiler/Hipoteca'),
            (46, 'es', 'Servicios Públicos'),
            (47, 'es', 'Internet y Teléfono'),
            (48, 'es', 'Mantenimiento del Hogar'),
            (49, 'es', 'Muebles');
            
            -- Insert English translations for Education subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (50, 'en', 'Tuition'),
            (51, 'en', 'Books & Supplies'),
            (52, 'en', 'Online Courses'),
            (53, 'en', 'Training');
            
            -- Insert Spanish translations for Education subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (50, 'es', 'Matrícula'),
            (51, 'es', 'Libros y Materiales'),
            (52, 'es', 'Cursos en Línea'),
            (53, 'es', 'Capacitación');
            
            -- Insert English translations for Travel subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (54, 'en', 'Flights'),
            (55, 'en', 'Hotels'),
            (56, 'en', 'Car Rental'),
            (57, 'en', 'Travel Insurance'),
            (58, 'en', 'Activities');
            
            -- Insert Spanish translations for Travel subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (54, 'es', 'Vuelos'),
            (55, 'es', 'Hoteles'),
            (56, 'es', 'Alquiler de Auto'),
            (57, 'es', 'Seguro de Viaje'),
            (58, 'es', 'Actividades');
            
            -- Insert English translations for Financial subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (59, 'en', 'Bank Fees'),
            (60, 'en', 'Investments'),
            (61, 'en', 'Insurance'),
            (62, 'en', 'Taxes'),
            (63, 'en', 'Loans');
            
            -- Insert Spanish translations for Financial subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (59, 'es', 'Comisiones Bancarias'),
            (60, 'es', 'Inversiones'),
            (61, 'es', 'Seguros'),
            (62, 'es', 'Impuestos'),
            (63, 'es', 'Préstamos');
            
            -- Insert English translations for Personal Care subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (64, 'en', 'Haircut'),
            (65, 'en', 'Cosmetics'),
            (66, 'en', 'Spa & Wellness');
            
            -- Insert Spanish translations for Personal Care subcategories
            INSERT INTO expenses_category_translation (master_id, language_code, name) VALUES
            (64, 'es', 'Corte de Pelo'),
            (65, 'es', 'Cosméticos'),
            (66, 'es', 'Spa y Bienestar');
            
            -- Update sequence for auto-increment
            SELECT setval('expenses_category_id_seq', 66, true);
            """,
            reverse_sql="""
            -- Delete all default categories and their translations
            DELETE FROM expenses_category_translation WHERE master_id IN (
                SELECT id FROM expenses_category WHERE is_default = true
            );
            DELETE FROM expenses_category WHERE is_default = true;
            
            -- Reset sequence
            SELECT setval('expenses_category_id_seq', 1, false);
            """
        ),
    ]