name: Deploy Django to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          echo "Deploying to EC2..."
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/api/
          git checkout main
          git fetch origin
          git reset --hard origin/main
          source venv/bin/activate
          sudo apt-get update
          sudo apt-get install -y libpq-dev python3-dev
          export DJANGO_SETTINGS_MODULE=family_expenses.settings.prod
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          deactivate
          EOF

      - name: Setup Gunicorn
        run: |
          echo "Setting up Gunicorn..."
          sudo bash -c 'cat > /etc/systemd/system/gunicorn.service <<EOF
          [Unit]
          Description=gunicorn daemon
          After=network.target
          [Service]
          User=ubuntu
          Group=www-data
          WorkingDirectory=/home/ubuntu/api/
          ExecStart=/home/ubuntu/api/venv/bin/gunicorn \
                    --access-logfile - \
                    --workers 3 \
                      --workers 3 --bind unix:/home/ubuntu/api/gunicorn.sock family_expenses.wsgi:application

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/gunicorn.service

            # Reload systemd and restart services
            sudo systemctl daemon-reload
            sudo systemctl enable gunicorn
            sudo systemctl restart gunicorn
            sudo nginx -t
            sudo systemctl reload nginx

            echo "✅ Deployment finished successfully!"
          EOF